name: Auto update upstream

on:
  push:
    branches: [main]

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set git config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Auto Update Bot"

      - name: Fetch upstream
        run: |
          git remote add upstream https://github.com/ORIGINAL_OWNER/ORIGINAL_REPOSITORY.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git merge --no-edit upstream/main

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          force: true
