name: Auto update upstream

on:
  push:
    branches: [main]

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set git config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Auto Update Bot"

      - name: Fetch upstream
        run: |
          git remote add lady https://github.com/Gnuyoah/Thread.git
          git fetch lady

      - name: Merge upstream changes
        run: |
          git merge --no-edit lady/main --allow-unrelated-histories

      - name: Push changes
        run: |
          git push origin main
          uses: ad-m/github-push-action@main
          with:
            branch: main
            github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
            force: true
            github_url: https://github.com
            directory: .
