name: Sync with Upstream
on:
  schedule:
    - cron: '0 * * * *'  # 每小时同步一次

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Upstream Branch
        uses: actions/checkout@v2
        with:
          repository: github.com/Gnuyoah/Thread.git  # 上游仓库信息
          ref: main  # 上游分支名称

      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          ref: main  # 本地分支名称

      - name: Merge Upstream Branch
        run: git merge upstream/upstream-branch --no-edit  # 合并上游分支到本地分支

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          branch: main
