name: Sync with Upstream

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  git-clone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/Gnuyoah/Thread.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
