name: Auto update upstream

on:
  push:
    branches: [main]

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Fetch upstream
        run: |
          git remote add lady https://github.com/Gnuyoah/Thread.git
          git fetch lady

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge lady main --allow-unrelated-histories

      - name: Push changes
        run: |
          git push origin main
