name: Sync with Upstream
on:
  schedule:
    - cron: '0 */2 * * *'  # 每隔两小时同步一次

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Upstream Branch
        uses: actions/checkout@v2
        with:
          repository: Gnuyoah/Thread  # 上游仓库的 owner 和 repo 名称
          ref: main  # 上游分支名称

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: main
