name: Sync with Upstream

on:
  schedule:
    - cron: '0 */2 * * *'  # 每两个小时同步一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Upstream Branch
        uses: actions/checkout@v2
        with:
          repository: Gnuyoah/Thread  # 上游仓库信息
          ref: main  # 上游分支名称

      - name: Add Upstream Remote
        run: git remote add lady https://github.com/Gnuyoah/Thread.git

      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          ref: main  # 本地分支名称

      - name: Merge Upstream Branch
        run: |
          git fetch lady
          git checkout main
          git merge --ff-only lady/main

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: main
