name: Auto update upstream

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 */6 * * *'  # 每6小时同步一次

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch upstream
        run: |
          git remote add lady https://github.com/Gnuyoah/Thread.git
          git fetch lady
          
      - name: Sync with upstream
        run: |
          git fetch lady
          git checkout main
          git merge lady/main --no-edit
          git push

    
