name: Auto update upstream

on:
  push:
    branches: [main]

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch upstream
        run: |
          git remote add upstream https://github.com/Gnuyoah/Thread.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream main --allow-unrelated-histories

      - name: Push changes
        run: |
          git push origin main
