name: Sync Repo

on:
  schedule:
    - cron: '0 * * * *' # 每小时同步一次

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2
        with:
          repository: Thread
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # 主仓库的访问令牌

      - name: Checkout forked repo
        uses: actions/checkout@v2
        with:
          repository: lady
          path: main

      - name: Sync changes
        run: |
          cd forked_repo
          git config user.name "Auto Update Bot"
          git config user.email "actions@github.com"
          git remote add upstream https://github.com/Gnuyoah/Thread.git
          git fetch upstream
          git merge upstream/main
          git push
