name: Sync with Upstream

on:
  schedule:
    - cron: '0 */2 * * *'  # 每两个小时同步一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Upstream Branch
        run: |
          git fetch upstream   
          git checkout main
          git merge upstream/main
